/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1)
	var __weex_template__ = __webpack_require__(5)
	var __weex_style__ = __webpack_require__(6)
	var __weex_script__ = __webpack_require__(7)

	__weex_define__('@weex-component/bfb0c893dd9292110cf7d9d26b4d2531', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})

	__weex_bootstrap__('@weex-component/bfb0c893dd9292110cf7d9d26b4d2531',undefined,undefined)

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(2)
	var __weex_style__ = __webpack_require__(3)
	var __weex_script__ = __webpack_require__(4)

	__weex_define__('@weex-component/symview', [], function(__weex_require__, __weex_exports__, __weex_module__) {

	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }

	    __weex_module__.exports.template = __weex_template__

	    __weex_module__.exports.style = __weex_style__

	})


/***/ },
/* 2 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "children": [
	    {
	      "type": "text",
	      "attr": {
	        "value": function () {return this.symtitle}
	      }
	    },
	    {
	      "type": "text",
	      "attr": {
	        "value": "gggggggggggggggggggggggggggggg"
	      }
	    }
	  ]
	}

/***/ },
/* 3 */
/***/ function(module, exports) {

	module.exports = {}

/***/ },
/* 4 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	    data: function () {return {
	        symtitle: 'gggggggggggggggg'
	    }},
	    methods: {
	        viewAppear: function viewAppear() {
	            this.symtitle = 'symview';
	        }
	    }
	};}
	/* generated by weex-loader */


/***/ },
/* 5 */
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "children": [
	    {
	      "type": "scroller",
	      "children": [
	        {
	          "type": "refresh",
	          "classList": [
	            "refresh-view"
	          ],
	          "attr": {
	            "display": function () {return this.refresh_display}
	          },
	          "events": {
	            "refresh": "loadData"
	          },
	          "children": [
	            {
	              "type": "text",
	              "shown": function () {return (this.refresh_display==='hide')},
	              "attr": {
	                "value": "↓ pull to refresh"
	              }
	            },
	            {
	              "type": "loading-indicator",
	              "classList": [
	                "indicator"
	              ]
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "style": {
	            "width": 750,
	            "height": 400
	          },
	          "children": [
	            {
	              "type": "slider",
	              "attr": {
	                "autoPlay": "true",
	                "interval": "1000"
	              },
	              "style": {
	                "height": 400,
	                "width": 750
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "repeat": function () {return this.banners},
	                  "attr": {
	                    "src": function () {return this.img}
	                  },
	                  "style": {
	                    "height": 400,
	                    "width": 750,
	                    "position": "absolute"
	                  }
	                }
	              ]
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "style": {
	            "height": 226.66,
	            "width": 750,
	            "flexDirection": "row"
	          },
	          "children": [
	            {
	              "type": "div",
	              "style": {
	                "width": 187.5,
	                "height": 226.66,
	                "borderWidth": 0.33,
	                "borderColor": "#dbdbdb",
	                "alignItems": "center"
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "style": {
	                    "width": 80,
	                    "height": 80,
	                    "backgroundColor": "#00FFFF",
	                    "marginTop": 40
	                  },
	                  "attr": {
	                    "src": "local://main"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 20,
	                    "fontSize": 24,
	                    "color": "#000000"
	                  },
	                  "attr": {
	                    "value": "基金理财"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 10,
	                    "fontSize": 20,
	                    "color": "#999999"
	                  },
	                  "attr": {
	                    "value": "工薪族优选"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "style": {
	                "width": 187.5,
	                "height": 226.66,
	                "borderWidth": 0.33,
	                "borderColor": "#dbdbdb",
	                "alignItems": "center"
	              },
	              "events": {
	                "click": "back"
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "style": {
	                    "width": 80,
	                    "height": 80,
	                    "backgroundColor": "#00FFFF",
	                    "marginTop": 40
	                  },
	                  "attr": {
	                    "src": "local://brand"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 20,
	                    "fontSize": 24,
	                    "color": "#000000"
	                  },
	                  "attr": {
	                    "value": "互联网金融"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 10,
	                    "fontSize": 20,
	                    "color": "#999999"
	                  },
	                  "attr": {
	                    "value": "一站式理财"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "style": {
	                "width": 187.5,
	                "height": 226.66,
	                "borderWidth": 0.33,
	                "borderColor": "#dbdbdb",
	                "alignItems": "center"
	              },
	              "events": {
	                "click": "push"
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "style": {
	                    "width": 80,
	                    "height": 80,
	                    "backgroundColor": "#00FFFF",
	                    "marginTop": 40
	                  },
	                  "attr": {
	                    "src": "local://shop"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 20,
	                    "fontSize": 24,
	                    "color": "#000000"
	                  },
	                  "attr": {
	                    "value": "理财保险"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 10,
	                    "fontSize": 20,
	                    "color": "#999999"
	                  },
	                  "attr": {
	                    "value": "稳健理财"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "style": {
	                "width": 187.5,
	                "height": 226.66,
	                "borderWidth": 0.33,
	                "borderColor": "#dbdbdb",
	                "alignItems": "center"
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "style": {
	                    "width": 80,
	                    "height": 80,
	                    "backgroundColor": "#00FFFF",
	                    "marginTop": 40
	                  },
	                  "attr": {
	                    "src": "local://my"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 20,
	                    "fontSize": 24,
	                    "color": "#000000"
	                  },
	                  "attr": {
	                    "value": "豆豆钱包"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "marginTop": 10,
	                    "fontSize": 20,
	                    "color": "#999999"
	                  },
	                  "attr": {
	                    "value": "资产增值管家"
	                  }
	                }
	              ]
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "style": {
	            "height": 226.66,
	            "width": 750,
	            "borderColor": "#dbdbdb",
	            "borderWidth": 0.33
	          },
	          "children": [
	            {
	              "type": "div",
	              "style": {
	                "height": 40,
	                "width": 750,
	                "marginTop": 20,
	                "flexDirection": "row"
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "style": {
	                    "backgroundColor": "#00FFFF",
	                    "marginLeft": 40,
	                    "marginTop": 10,
	                    "width": 20,
	                    "height": 20
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "color": "#ff6600",
	                    "fontSize": 34,
	                    "marginLeft": 10,
	                    "flex": 2
	                  },
	                  "attr": {
	                    "value": "储蓄宝"
	                  }
	                },
	                {
	                  "type": "text",
	                  "style": {
	                    "color": "#999999",
	                    "fontSize": 20,
	                    "marginRight": 40,
	                    "marginTop": 10
	                  },
	                  "attr": {
	                    "value": "我的储蓄我做主"
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "style": {
	                "alignItems": "center",
	                "marginTop": 40
	              },
	              "children": [
	                {
	                  "type": "text",
	                  "style": {
	                    "color": "#ff6600",
	                    "fontSize": 60
	                  },
	                  "attr": {
	                    "value": function () {return this.piggyValue}
	                  }
	                }
	              ]
	            },
	            {
	              "type": "div",
	              "style": {
	                "alignItems": "center"
	              },
	              "children": [
	                {
	                  "type": "text",
	                  "style": {
	                    "fontSize": 20,
	                    "color": "#999999",
	                    "marginTop": 10
	                  },
	                  "attr": {
	                    "value": "七日年化收益率(%)"
	                  }
	                }
	              ]
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "style": {
	            "width": 750,
	            "height": 100,
	            "flexDirection": "row"
	          },
	          "children": [
	            {
	              "type": "text",
	              "style": {
	                "width": 200,
	                "height": 60,
	                "marginLeft": 40,
	                "marginTop": 30,
	                "color": "#ff6600"
	              },
	              "attr": {
	                "value": "金融快讯"
	              }
	            },
	            {
	              "type": "slider",
	              "attr": {
	                "autoPlay": "true",
	                "interval": "1000"
	              },
	              "style": {
	                "height": 100,
	                "width": 470
	              },
	              "children": [
	                {
	                  "type": "div",
	                  "style": {
	                    "height": 100,
	                    "width": 470
	                  },
	                  "repeat": function () {return this.news},
	                  "children": [
	                    {
	                      "type": "text",
	                      "style": {
	                        "flexDirection": "column",
	                        "marginTop": 40,
	                        "fontSize": 20
	                      },
	                      "attr": {
	                        "value": function () {return this.newsText}
	                      }
	                    }
	                  ]
	                }
	              ]
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "style": {
	            "width": 750,
	            "height": 267,
	            "backgroundColor": "#efefef"
	          },
	          "children": [
	            {
	              "type": "slider",
	              "attr": {
	                "autoPlay": "true",
	                "interval": "2000"
	              },
	              "style": {
	                "width": 750,
	                "height": 226,
	                "marginTop": 20
	              },
	              "children": [
	                {
	                  "type": "image",
	                  "repeat": function () {return this.adNews},
	                  "attr": {
	                    "src": function () {return this.img}
	                  }
	                }
	              ]
	            }
	          ]
	        },
	        {
	          "type": "symview",
	          "attr": {
	            "symtitle": "ffffffffffffffffff"
	          },
	          "style": {
	            "backgroundColor": "#00FFFF",
	            "width": 375
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ },
/* 6 */
/***/ function(module, exports) {

	module.exports = {
	  "ct": {
	    "width": 750,
	    "alignItems": "center",
	    "justifyContent": "center"
	  },
	  "img": {
	    "marginBottom": 20
	  },
	  "indicator": {
	    "height": 40,
	    "width": 40,
	    "color": "#45b5f0"
	  },
	  "refresh-arrow": {
	    "fontSize": 30,
	    "color": "#45b5f0"
	  },
	  "refresh-view": {
	    "width": 750,
	    "height": 100,
	    "display": "flex",
	    "MsFlexAlign": "center",
	    "WebkitAlignItems": "center",
	    "WebkitBoxAlign": "center",
	    "alignItems": "center",
	    "bottom": 1206
	  },
	  "loading-view": {
	    "width": 750,
	    "height": 100,
	    "display": "flex",
	    "MsFlexAlign": "center",
	    "WebkitAlignItems": "center",
	    "WebkitBoxAlign": "center",
	    "alignItems": "center"
	  }
	}

/***/ },
/* 7 */
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';

	module.exports = {
	  data: function () {return {
	    mainData: undefined,
	    refresh_display: 'hide',
	    list: [{ name: '123', price: 100 }, { name: '345', price: 500 }, { name: '567', price: 1.5 }],
	    piggyValue: 10,
	    adNews: [],
	    news: [],
	    banners: []

	  }},

	  methods: {
	    refresh: function refresh(e) {

	      this.loadData();
	    },
	    push: function push() {
	      var params = {
	        'url': 'local://SymView.js',
	        'animated': 'true'
	      };

	      var event = __weex_require__('@weex-module/event');
	      event.openURL(params.url);
	    },
	    back: function back() {
	      var params = {
	        'url': 'SymView.we',
	        'animated': 'true'
	      };
	      var navigator = __weex_require__('@weex-module/navigator');
	      navigator.pop(params, function (e) {});
	    },
	    loadData: function loadData() {
	      this.refresh_display = 'show';
	      var stream = __weex_require__('@weex-module/stream');
	      stream.fetch({
	        method: 'GET',
	        url: 'http://www.doodoabc.com/app_index',
	        headers: {
	          'app-ver': 'ios_2.0.4'
	        },

	        type: 'json'

	      }, function (retdata) {
	        this.refresh_display = 'hide';
	        this.mainData = retdata.data.data;
	        this.piggyValue = this.mainData.piggy.sumOfNav;
	        var banners = [];
	        this.banners = [];
	        for (var i = 0; i < this.mainData.app_index_slider.list.length; i++) {
	          var slider = this.mainData.app_index_slider.list[i];
	          banners.push({ img: slider.adData.pic_url });
	        }

	        var adNews = [];
	        for (var i = 0; i < this.mainData.app_index_banner_slider.list.length; i++) {
	          var slider = this.mainData.app_index_banner_slider.list[i];
	          adNews.push({ img: slider.adData.pic_url });
	        }
	        this.adNews = adNews;
	        var news = [];
	        for (var i = 0; i < this.mainData.thePage.length; i++) {
	          var info = this.mainData.thePage[i];

	          news.push({ newsText: info.title });
	        }
	        this.news = news;
	        var fundList = this.mainData.app_index_fund.list;
	        var list = [];
	        for (var i = 0; i < 100; i++) {
	          var fund = fundList[i % fundList.length];
	          if (fund.prodData !== undefined) {

	            list.push({ name: fund.prodData.FUND_NAME, price: fund.prodData.YEAR_RATE1 });
	          }
	        }
	        this.list = list;
	      }.bind(this), function (response) {
	        console.log(response);
	        console.log('ffffffffff');
	      });
	    }
	  },
	  created: function created() {
	    console.log('dddddddd');
	  }
	};}
	/* generated by weex-loader */


/***/ }
/******/ ]);